source "https://rubygems.org"

gem "bcrypt"
gem "graphql"
gem "jwt"
gem "mongoid"
gem "puma"
gem "rack-contrib"
gem "search_object_graphql"
gem "sinatra"
gem "sinatra-contrib"
group :test do
  gem "database_cleaner-mongoid"
  gem "factory_bot"
  gem "mongoid-rspec"
end
